name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io/robinjesson"
  REPOSITORY: "budget-api"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        run: |
          docker build -t ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{github.ref_name}}-${{github.run_number}} . 
          docker push ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{github.ref_name}}-${{github.run_number}}