name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t budget-api:${GITHUB_REF_NAME}.${GITHUB_SHA} .
      - name: Push Docker Image to GitHub Packages
        run: docker push p.io/robinjesson/budget-api