name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: sudo apt-get install docker-ce
      - name: Build Docker Image
        run: docker build -t my-docker-image:${GITHUB_REF_NAME} .
      - name: Push Docker Image to GitHub Packages
        run: docker push ghcr.io/<your-github-username>/my-docker-image:${GITHUB_REF_NAME}