name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io/robinjesson"
  REPOSITORY: "budget-api"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t ${REGISTRY}/${REPOSITORY}:${github.ref_name}.${github.sha} .
      - name: Push docker image
        run: docker push ${REGISTRY}/${REPOSITORY}:${github.ref_name}.${github.sha}