name: Build and Push Docker Image

# This workflow will build and push a Docker image to GitHub Packages
# whenever a push is made to the main branch.

on:
  push:
    branches:
      - main

# This job will run on Ubuntu 20.04.

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    # This step checks out the code from the repository.
    steps:
      - uses: actions/checkout@v2

    # This step installs Docker.
    - name: Install Docker
      run: sudo apt-get install docker-ce

    # This step builds the Docker image.
    - name: Build Docker Image
      run: docker build -t budget-api:main.${GITHUB_REF_NAME} .

    # This step pushes the Docker image to GitHub Packages.
    - name: Push Docker Image to GitHub Packages
      run: docker push ghcr.io/robinjesson/budget-api:main.${GITHUB_REF_NAME}